### ISSUE TITLE
Wtf 

### ISSUE THREAD

**Issue by Aliuihb** [cemahseri/DankMemerEventCatcher#1]
Hat command shuld i use to run it????????? U did not type the commands on readme.md
Im i dump just update it type the commands to run it pls

**Comment by cemahseri** [comment]
Well, just run the `DankMemerEventCatcher.exe` file, which is the only executable file among 3 files.

**Comment by Aliuihb** [comment]
Bruh
Im U-sving replit.com and dont know how to run :/

**Comment by cemahseri** [comment]
bruh momento numero uno

Well, this is not a bot. This is a selfbot, which replies to events of the Dank Memer bot in order to gain items and coin. I just wanted to clarify. And as I know, Replit runs their repls on Linux. You cannot run .exe files on Linux directly. If you want, you can compile the source code with Mono and run it on Linux. Alternatively, you can install Wine on your repl somehow and get the .exe file running.
